$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

display_name: random_forest_training_pipeline
experiment_name: used-car-price-prediction
description: >
  End-to-end Azure ML pipeline for used car price prediction using Random Forest Regressor.
  This pipeline includes data preparation, hyperparameter sweep, and model registration.

inputs:
  raw_data:
    type: uri_file
    path: azureml:used-cars-data@latest

outputs:
  train_data:
    type: uri_file
  test_data:
    type: uri_file
  model_info_output_path:
    type: uri_file

settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:cpu-cluster
  continue_on_step_failure: false

jobs:

  # =========================================================
  # STEP 1: Data Preparation
  # =========================================================
  prep_data:
    name: prep_data
    display_name: Data Preparation
    description: Read raw data, preprocess, split into train/test datasets, and save outputs.
    code: ../../../data-science/src
    command: >-
      python prep.py
      --raw_data ${{inputs.raw_data}}
      --train_data ${{outputs.train_data}}
      --test_data ${{outputs.test_data}}
    environment: azureml:used-cars-train-env@latest
    inputs:
      raw_data: ${{parent.inputs.raw_data}}
    outputs:
      train_data: ${{parent.outputs.train_data}}
      test_data: ${{parent.outputs.test_data}}

  # =========================================================
  # STEP 2: Random Forest Training with Hyperparameter Sweep
  # =========================================================
  sweep_step:
    name: sweep_job
    display_name: Random Forest Hyperparameter Sweep
    description: Perform random search over RandomForestRegressor hyperparameters.
    type: sweep
    inputs:
      train_data: ${{parent.jobs.prep_data.outputs.train_data}}
      test_data: ${{parent.jobs.prep_data.outputs.test_data}}
    outputs:
      model_output:
        type: mlflow_model

    # Random sampling for hyperparameter optimization
    sampling_algorithm: random
    trial: ./train.yml  # Defines the Random Forest training logic

    # ------------------------
    # Hyperparameter Search Space
    # ------------------------
    search_space:
      n_estimators:
        type: choice
        values: [50, 100, 200, 300]
      max_depth:
        type: choice
        values: [5, 10, 20, 30]
      min_samples_split:
        type: choice
        values: [2, 5, 10]
      min_samples_leaf:
        type: choice
        values: [1, 2, 4]
      max_features:
        type: choice
        values: ["auto", "sqrt", "log2"]

    # ------------------------
    # Optimization Objective
    # ------------------------
    objective:
      goal: minimize
      primary_metric: MSE

    # ------------------------
    # Sweep Constraints
    # ------------------------
    limits:
      max_total_trials: 20
      max_concurrent_trials: 5
      timeout: 10800  # 3 hours

    environment: azureml:used-cars-train-env@latest

  # =========================================================
  # STEP 3: Model Registration
  # =========================================================
  register_model:
    name: register_model
    display_name: Register Trained Random Forest Model
    description: Register the best performing Random Forest model into Azure ML registry.
    code: ../../../data-science/src
    command: >-
      python register.py
      --model_name ${{inputs.model_name}}
      --model_path ${{inputs.model_path}}
      --model_info_output_path ${{outputs.model_info_output_path}}
    environment: azureml:used-cars-train-env@latest
    inputs:
      model_name: "used_cars_price_prediction_rf_model"
      model_path: ${{parent.jobs.sweep_step.outputs.model_output}}
    outputs:
      model_info_output_path: ${{parent.outputs.model_info_output_path}}
